# comentário
version: '3'

# comentário
services:
  # comentário
  api-v1:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: phmiranda/nginx-custom
    container_name: nginx-custom
    ports:
      - "9000:80"
    networks:
      - desenvolvimento-network
    depends_on:
      - "api-v3"
      - "api-v4"
      - "api-v5"

  # comentário
  #api-v2:
  #  build:
  #    dockerfile: ./docker/node.dockerfile
  #   context: .
  # image: phmiranda/node-custom
  #  container_name: node-custom
  #  ports:
  #    - "9001:3000"
  #  networks:
  #    - desenvolvimento-network

  # comentário
  api-v3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: phmiranda/alura-books
    container_name: alura-books-v1
    ports:
      - "9002:3000"
    networks:
      - desenvolvimento-network
    depends_on:
      - "database-mongo"

  # comentário
  api-v4:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: phmiranda/alura-books
    container_name: alura-books-v2
    ports:
      - "9003:3000"
    networks:
      - desenvolvimento-network
    depends_on:
      - "database-mongo"

  # comentário
  api-v5:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: phmiranda/alura-books
    container_name: alura-books-v3
    ports:
      - "9004:3000"
    networks:
      - desenvolvimento-network
    depends_on:
      - "database-mongo"

  # comentário
  database-mongo:
    image: mongo
    networks:
      - desenvolvimento-network

# comentário
networks:
  desenvolvimento-network:
    driver: bridge

